@startuml systemstructure
!theme cerulean-outline
skinparam packageStyle folder

package CompanyManager.ConApp {
    class Program {

    }
}

package CompanyManager.Logic {
    package DataContext {
        class Factory {

        }
    }
}

package CompanyManager.Common {
    package Contracts {
        interface IIdentifiable {
            + Id : int
        }
        interface ICompany {
            + Name : string
            + Address : string
            ---
            + CopyProperties(company : ICompany) : void
        }
        interface ICustomer {
            + CompanyId : int
            + Name : string
            + Email : string
            ---
            + CopyProperties(customer : ICustomer) : void
        }
        interface IEmployee {
            + CompanyId : int
            + FirstName : string
            + LastName : string
            + Email : string
            ---
            + CopyProperties(employee : IEmployee) : void
        }
        ICompany -|> IIdentifiable
        ICustomer -|> IIdentifiable
        IEmployee -|> IIdentifiable
    }
}

CompanyManager.Logic --> CompanyManager.Common : imports
CompanyManager.ConApp --> CompanyManager.Common : imports
@enduml
